server:
  port: 8044
  servlet:
    contextPath: /user-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  ### Azure Database connection
  datasource:
    url: jdbc:postgresql://ec2-52-31-219-113.eu-west-1.compute.amazonaws.com:5432/d839f9utocukpj?sslmode=require&user=leedcsdusxkjwu&password=1c45b5556b69823e703b00c1a19865f512b253ec4f36bf00585158fcc0003e60

#    url: jdbc:postgresql://db-parcel-manage-b.postgres.database.azure.com/postgres?sslmode=require
#    username: db_parcel_manage@db-parcel-manage-b
#    password: lkjuhsfeouwt9oqAFWGh233rpofhEGHETqjha09gq2aGDHFoilr3nkw
#    initialization-mode: always
#create database minimum 25 dollar per month
#verbindingsbeveiliging add ip-adres: 80.115.79.202


#### AWS Database connection
#    datasource:
#        url: jdbc:postgresql://db-parcel-manage.c4q0tlndzabx.us-east-1.rds.amazonaws.com:5432/postgres
#        username: db_parcel_manage
#        password: lkjuhsfeouwt9oqAFWGh233rpofhEGHETqjha09gq2aGDHFoilr3nkw
#        initialization-mode: always